### ISSUE TITLE
Activations should also track the input

### ISSUE THREAD

**Issue by ScottChapman** [apache/incubator-openwhisk#3242] opened 2018-02-01 17:20 UTC
## Environment details:
IBM Cloud

## Steps to reproduce the issue:

1.   activate an action
2.   bx wsk activation get <id>
3.   

## Provide the expected results and outputs:

expected a request field which was the input to main

## Provide the actual results and outputs:

Response is given, but no request

**Comment by rabbah** [comment] 2018-02-07 15:54
Duplicate of https://github.com/apache/incubator-openwhisk/issues/1188.
The recommended solution is to use `echo` action for standalone actions.
For compositions and sequences, the input is inferred from the previous action's result.

**Closed by rabbah** 2018-02-07 15:54 UTC
