### ISSUE TITLE
docker-pull-lean' failed

### ISSUE THREAD

**Issue by SamChb72** [apache/incubator-openwhisk#4548] opened 2019-07-07 13:17 UTC
## Environment details:

* local deployment, vagrant, native ubuntu, Mac OS, Bluemix, ...   
* version of docker, vagrant, ubuntu, ...

## Steps to reproduce the issue:

1.   
2.   
3.   

## Provide the expected results and outputs:

```
output comes here
```

## Provide the actual results and outputs:

```
output comes here
```

## Additional information you deem important:
* issue happens only occasionally or under certain circumstances   
* changes you did or observed in the environment

**Comment by rabbah** [comment] 2019-07-07 14:54
duplicate of #4549.

**Closed by rabbah** 2019-07-07 14:54 UTC
