### ISSUE TITLE
Python Packages Install Fails in Docker action

### ISSUE THREAD

**Issue by Abiwax** [apache/incubator-openwhisk#2180] opened 2017-04-25 13:41 UTC
Can't install Python packages like Numpy in Docker because of the absence of certain libraries.
Packages only install if the below command is included in docker file, is it possible to integrate this in the Docker Skeleton.

RUN mkdir -p /tmp/build \
&& cd /tmp/build/ \
&& wget http://www.netlib.org/blas/blas-3.6.0.tgz \
&& wget http://www.netlib.org/lapack/lapack-3.6.1.tgz \
&& tar xzf blas-3.6.0.tgz \
&& tar xzf lapack-3.6.1.tgz \
&& cd /tmp/build/BLAS-3.6.0/ && gfortran -O3 -std=legacy -m64 -fno-second-underscore -fPIC -c *.f \
&& ar r libfblas.a *.o && ranlib libfblas.a && mv libfblas.a /tmp/build/. \
&& cd /tmp/build/lapack-3.6.1/ \
&& sed -e "s/frecursive/fPIC/g" -e "s/ \.\.\// /g" -e "s/^CBLASLIB/\#CBLASLIB/g" make.inc.example > make.inc \
&& make lapacklib \
&& make clean \
&& mv liblapack.a /tmp/build/. \
&& cd / \
&& export BLAS=/tmp/build/libfblas.a \
&& export LAPACK=/tmp/build/liblapack.a \
&& cd /action; pip install -r requirements.txt \
&& rm -r /tmp/build

**Comment by rabbah** [comment] 2017-04-25 14:27
Partially related to #1980 and allowing for more runtime kinds.

**Comment by rabbah** [comment] 2017-06-22 03:00
I will close this as duplicate of https://github.com/apache/incubator-openwhisk/issues/2300.

**Closed by rabbah** 2017-06-22 03:00 UTC
Labels: runtime
