### ISSUE TITLE
wsk cli should list available runtime "kinds" 

### ISSUE THREAD

**Issue by ashishth09** [apache/incubator-openwhisk#2467] opened 2017-07-10 17:06 UTC
It is a feature request. I think it is something which can be achieved by hitting  http://openwhisk.ng.bluemix.net for example and parsing runtimes kind.

**Comment by starpit** [comment] 2017-07-11 11:49
possible duplicate of #335 ?

**Comment by rabbah** [comment] 2017-11-25 02:46
Issue moved to [apache/incubator-openwhisk-cli #167](https://github.com/apache/incubator-openwhisk-cli/issues/167) via [**ZenHub**](https://www.zenhub.com/)

**Closed by rabbah** 2017-11-25 02:46 UTC
