### ISSUE TITLE
./gradlew distDocker Failed

### ISSUE THREAD

**Issue by DQvsRA** [apache/incubator-openwhisk#2829] opened 2017-10-02 20:25 UTC
## Environment details:
Armbian (Debian 8)

## Steps to reproduce the issue:

1.   Just git pull
2.   ./gradlew distDocker

## Provide the actual results and outputs:

```
 ---> 7a58ec32ff71
Removing intermediate container 7c650cf552bc
Successfully built 7a58ec32ff71
Successfully tagged scala:latest
Building 'scala' took 6 minutes, 16.822 seconds
:common:scala:tagImage
Mon Oct 02 22:18:59 CEST 2017: Executing 'docker tag scala whisk/scala:latest'
:common:scala:pushImage SKIPPED
:core:actionProxy:distDocker
Mon Oct 02 22:18:59 CEST 2017: Executing 'docker build -t dockerskeleton /root/o                 penwhisk/core/actionProxy'
Sending build context to Docker daemon  24.06kB

Step 1/9 : FROM python:3.6.1-alpine
3.6.1-alpine: Pulling from library/python
90f4dba627d6: Pulling fs layer
19bc0bb0be9f: Pulling fs layer
e05eff433916: Pulling fs layer
e70196200a87: Pulling fs layer
a6d780959950: Pulling fs layer
e70196200a87: Waiting
a6d780959950: Waiting
19bc0bb0be9f: Verifying Checksum
e70196200a87: Verifying Checksum
e70196200a87: Download complete
90f4dba627d6: Verifying Checksum
90f4dba627d6: Download complete
90f4dba627d6: Pull complete
a6d780959950: Verifying Checksum
a6d780959950: Download complete
19bc0bb0be9f: Pull complete
e05eff433916: Verifying Checksum
e05eff433916: Download complete
e05eff433916: Pull complete
e70196200a87: Pull complete
a6d780959950: Pull complete
Digest: sha256:0945574465b917d524ce9b748479a286c2ed3c5a97311ac5950464907d4d8b53
Status: Downloaded newer image for python:3.6.1-alpine
 ---> ddd6300d05a3
Step 2/9 : RUN apk add --no-cache bash  && apk add --no-cache --virtual .build-d                 eps         bzip2-dev         gcc         libc-dev   && pip install --upgrade pi                 p setuptools six   && pip install --no-cache-dir gevent==1.2.1 flask==0.12   &&                  apk del .build-deps
 ---> Running in deaba6e79356
standard_init_linux.go:187: exec user process caused "exec format error"
The command '/bin/sh -c apk add --no-cache bash  && apk add --no-cache --virtual                  .build-deps         bzip2-dev         gcc         libc-dev   && pip install --u                 pgrade pip setuptools six   && pip install --no-cache-dir gevent==1.2.1 flask==0                 .12   && apk del .build-deps' returned a non-zero code: 1

Mon Oct 02 22:20:06 CEST 2017: Command 'docker build -t dockerskeleton /root/ope                 nwhisk/core/actionProxy' failed with exitCode 1, 2 retries left, retrying...
Mon Oct 02 22:20:06 CEST 2017: Executing 'docker build -t dockerskeleton /root/o                 penwhisk/core/actionProxy'
Sending build context to Docker daemon  24.06kB

Step 1/9 : FROM python:3.6.1-alpine
 ---> ddd6300d05a3
Step 2/9 : RUN apk add --no-cache bash  && apk add --no-cache --virtual .build-d                 eps         bzip2-dev         gcc         libc-dev   && pip install --upgrade pi                 p setuptools six   && pip install --no-cache-dir gevent==1.2.1 flask==0.12   &&                  apk del .build-deps
 ---> Running in c5273c1dd0fe
standard_init_linux.go:187: exec user process caused "exec format error"
The command '/bin/sh -c apk add --no-cache bash  && apk add --no-cache --virtual                  .build-deps         bzip2-dev         gcc         libc-dev   && pip install --u                 pgrade pip setuptools six   && pip install --no-cache-dir gevent==1.2.1 flask==0                 .12   && apk del .build-deps' returned a non-zero code: 1

Mon Oct 02 22:20:10 CEST 2017: Command 'docker build -t dockerskeleton /root/ope                 nwhisk/core/actionProxy' failed with exitCode 1, 1 retries left, retrying...
Mon Oct 02 22:20:10 CEST 2017: Executing 'docker build -t dockerskeleton /root/o                 penwhisk/core/actionProxy'
Sending build context to Docker daemon  24.06kB

Step 1/9 : FROM python:3.6.1-alpine
 ---> ddd6300d05a3
Step 2/9 : RUN apk add --no-cache bash  && apk add --no-cache --virtual .build-d                 eps         bzip2-dev         gcc         libc-dev   && pip install --upgrade pi                 p setuptools six   && pip install --no-cache-dir gevent==1.2.1 flask==0.12   &&                  apk del .build-deps
 ---> Running in c429db9196d9
standard_init_linux.go:187: exec user process caused "exec format error"
The command '/bin/sh -c apk add --no-cache bash  && apk add --no-cache --virtual                  .build-deps         bzip2-dev         gcc         libc-dev   && pip install --u                 pgrade pip setuptools six   && pip install --no-cache-dir gevent==1.2.1 flask==0                 .12   && apk del .build-deps' returned a non-zero code: 1

Mon Oct 02 22:20:15 CEST 2017: Command 'docker build -t dockerskeleton /root/ope                 nwhisk/core/actionProxy' failed with exitCode 1, no more retries left, aborting.                 ..
:core:actionProxy:distDocker FAILED
:core:actionProxy:tagImage
Mon Oct 02 22:20:15 CEST 2017: Executing 'docker tag dockerskeleton whisk/docker                 skeleton:latest'
Error response from daemon: No such image: dockerskeleton:latest
Mon Oct 02 22:20:15 CEST 2017: Command 'docker tag dockerskeleton whisk/dockersk                 eleton:latest' failed with exitCode 1, 2 retries left, retrying...
Mon Oct 02 22:20:15 CEST 2017: Executing 'docker tag dockerskeleton whisk/docker                 skeleton:latest'
Error response from daemon: No such image: dockerskeleton:latest
Mon Oct 02 22:20:15 CEST 2017: Command 'docker tag dockerskeleton whisk/dockersk                 eleton:latest' failed with exitCode 1, 1 retries left, retrying...
Mon Oct 02 22:20:15 CEST 2017: Executing 'docker tag dockerskeleton whisk/docker                 skeleton:latest'
Error response from daemon: No such image: dockerskeleton:latest
Mon Oct 02 22:20:15 CEST 2017: Command 'docker tag dockerskeleton whisk/dockersk                 eleton:latest' failed with exitCode 1, no more retries left, aborting...
:core:actionProxy:tagImage FAILED

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Script '/root/openwhisk/gradle/docker.gradle' line: 96

* What went wrong:
Execution failed for task ':core:actionProxy:distDocker'.
> Mon Oct 02 22:20:15 CEST 2017: Command 'docker build -t dockerskeleton /root/o                 penwhisk/core/actionProxy' failed with exitCode 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug                  option to get more log output.
==============================================================================

2: Task failed with an exception.
-----------
* Where:
Script '/root/openwhisk/gradle/docker.gradle' line: 96

* What went wrong:
Execution failed for task ':core:actionProxy:tagImage'.
> Mon Oct 02 22:20:15 CEST 2017: Command 'docker tag dockerskeleton whisk/docker                 skeleton:latest' failed with exitCode 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug                  option to get more log output.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 9m 40s
```

**Comment by markusthoemmes** [comment] 2017-10-02 20:33
Since you're running armbian, I assume you're running on ARM hardware?

The error message you're getting is related to running binaries of x86 on ARM:

```
standard_init_linux.go:187: exec user process caused "exec format error"
```

Got no quick fix for that. Apparently, there are alpine base images for ARM specifically.

**Comment by rabbah** [comment] 2019-06-25 22:53
closing as duplicate of https://github.com/apache/incubator-openwhisk/issues/3172.

**Closed by rabbah** 2019-06-25 22:53 UTC
Labels: build
