### ISSUE TITLE
Add support for docker actions from Bluemix registry

### ISSUE THREAD

**Issue by mpuittinen** [apache/incubator-openwhisk#1933] opened 2017-03-02 10:50 UTC
Openwhisk currently only supports docker actions from public Dockerhub registry. Access to Dockerhub may be slow (introduce additional load time to cold starts) and also requires, that you make your docker image public (may have IPR / licencing issues)

Please add support for docker images from the Bluemix Container Service registry.

**Comment by rabbah** [comment] 2017-06-22 03:21
Closing as duplicate of https://github.com/apache/incubator-openwhisk/issues/1933.

**Closed by rabbah** 2017-06-22 03:21 UTC
