### ISSUE TITLE
wsk cli on linux: bug with parameters

### ISSUE THREAD

**Issue by starpit** [apache/incubator-openwhisk#1689] opened 2017-01-05 02:50 UTC
try this repo: https://github.com/starpit/openwhisk-fuseki

do an
```
% ./init.sh
% ./test.sh
```

on mac, `test.sh` succeeds. on linux, it fails, with `wsk` complaining about newlines that clearly are not there.

```
[sk-cli/commands/action.go]:158:[Inf] Parsing parameters: []string{"{\"query\": \"UFJFRklYIHhzZDogPGh0dHA6Ly93d3cudzMub3JnLzIwMDEvWE1MU2NoZW1hIz4KUFJFRklYIGRj\nOiA8aHR0cDovL3B1cmwub3JnL2RjL2VsZW1lbnRzLzEuMS8+ClBSRUZJWCA6IDwuPgoKU0VMRUNU\nICoKeyA/cyA/cCA/byB9\"}", "{\"model\": \"QHByZWZpeCBkYzogICAgIDxodHRwOi8vcHVybC5vcmcvZGMvZWxlbWVudHMvMS4xLz4gLgpAcHJl\nZml4IHhzZDogICAgPGh0dHA6Ly93d3cudzMub3JnLzIwMDEvWE1MU2NoZW1hIz4gLgpAcHJlZml4\nIHdlYjogICAgPGh0dHA6Ly9leGFtcGxlLz4gLgoKPGRzLW5nLTEudHRsPiAgZGM6ZGF0ZSAiMjAw\nNS0wNy0xNFQwMzoxODo1NiswMTowMCJeXnhzZDpkYXRlVGltZSAuCjxkcy1uZy0yLnR0bD4gIGRj\nOmRhdGUgIjIwMDUtMDktMjJUMDU6NTM6MDUrMDE6MDAiXl54c2Q6ZGF0ZVRpbWUgLg==\"}", "{\"lang\": \"ttl\"}"}
[mmands.getJSONFromStrings]:167:[Err] Invalid JSON detected for '{"query": "UFJFRklYIHhzZDogPGh0dHA6Ly93d3cudzMub3JnLzIwMDEvWE1MU2NoZW1hIz4KUFJFRklYIGRj
OiA8aHR0cDovL3B1cmwub3JnL2RjL2VsZW1lbnRzLzEuMS8+ClBSRUZJWCA6IDwuPgoKU0VMRUNU
ICoKeyA/cyA/cCA/byB9"}'
[sk-cli/commands/action.go]:162:[Err] getJSONFromStrings([]string{"{\"query\": \"UFJFRklYIHhzZDogPGh0dHA6Ly93d3cudzMub3JnLzIwMDEvWE1MU2NoZW1hIz4KUFJFRklYIGRj\nOiA8aHR0cDovL3B1cmwub3JnL2RjL2VsZW1lbnRzLzEuMS8+ClBSRUZJWCA6IDwuPgoKU0VMRUNU\nICoKeyA/cyA/cCA/byB9\"}", "{\"model\": \"QHByZWZpeCBkYzogICAgIDxodHRwOi8vcHVybC5vcmcvZGMvZWxlbWVudHMvMS4xLz4gLgpAcHJl\nZml4IHhzZDogICAgPGh0dHA6Ly93d3cudzMub3JnLzIwMDEvWE1MU2NoZW1hIz4gLgpAcHJlZml4\nIHdlYjogICAgPGh0dHA6Ly9leGFtcGxlLz4gLgoKPGRzLW5nLTEudHRsPiAgZGM6ZGF0ZSAiMjAw\nNS0wNy0xNFQwMzoxODo1NiswMTowMCJeXnhzZDpkYXRlVGltZSAuCjxkcy1uZy0yLnR0bD4gIGRj\nOmRhdGUgIjIwMDUtMDktMjJUMDU6NTM6MDUrMDE6MDAiXl54c2Q6ZGF0ZVRpbWUgLg==\"}", "{\"lang\": \"ttl\"}"}, false) failed: invalid character '\n' in string literal
```

**Comment by dubeejw** [comment] 2017-01-31 20:55
An error occurs because invalid JSON is being passed to the CLI. You must replace the \n character 
```
Below is the error I see when using the query parameter you posted. You must escape the new line as required by the JSON specification. For more information see: http://www.json.org/.

error: Unable to parse action command arguments: Invalid parameter argument '[]string{"{\n\t\"query\": \"UFJFRklYIHhzZDogPGh0dHA6Ly93d3cudzMub3JnLzIwMDEvWE1MU2NoZW1hIz4KUFJFRklYIGRj\\nOiA8aHR0cDovL3B1cmwub3JnL2RjL2VsZW1lbnRzLzEuMS8+ClBSRUZJWCA6IDwuPgoKU0VMRUNU\\nICoKeyA/cyA/cCA/byB9\\\"\n}\n"}': invalid character '\n' in string literal
```

**Comment by dubeejw** [comment] 2017-02-07 21:38
@csantanapr, I believe this can be closed as well.

**Comment by starpit** [comment] 2017-02-07 21:55
the point of this bug report was that, on linux, the CLI is adding the newlines.

**Comment by starpit** [comment] 2017-02-07 21:57
```
$WSK action invoke fuseki -b -r \
    -p query "`base64 examples/q-ds-1.rq`" \
    -p model "`base64 examples/ds-dft.ttl`" \
    -p lang ttl
```

note how the inputs are either a simple string ("ttl"), or base64-encoded files, which certainly contain no newlines

**Comment by csantanapr** [comment] 2017-02-07 22:03
@starpit thanks for the pointer, so is still fails for you on linux on latest cli version?

@dubeejw Did you verify that it works on linux now? Also is there a test case that can cover this?

**Comment by dubeejw** [comment] 2017-02-07 22:09
Since the input works properly on Mac, I suspect linux is converting those escaped newline characters into actual new lines when passing the information to the CLI.

**Comment by starpit** [comment] 2017-02-07 22:21
i have verified that this is still a problem with the latest CLI

**Comment by starpit** [comment] 2017-02-07 22:30
interesting: it appears that the `base64` executable tacks a newline on the end. it does so on both macos and linux, but, for some reason, the macos `wsk` CLI is resilient to this.

**Comment by mdeuser** [comment] 2017-05-24 16:52
despite the inconsistent platform-specific Go parsing of the input, it sounds like the root cause of this issue is that `base64` is generating the \n which results in a non-compliant JSON string value.

ok to close?

**Comment by csantanapr** [comment] 2017-11-22 03:03
>despite the inconsistent platform-specific Go parsing of the input, it sounds like the root cause of this issue is that base64 is generating the \n which results in a non-compliant JSON string value.

**Closed by csantanapr** 2017-11-22 03:03 UTC
Labels: bug, cli
