### ISSUE TITLE
Improve error message saying "Request defines parameters that are not allowed (e.g., reserved properties)."

### ISSUE THREAD

**Issue by andreasnauerz** [apache/incubator-openwhisk#2790] opened 2017-09-21 13:36 UTC
## Environment details:

* Bluemix

## Steps to reproduce the issue:

1.  Log into Bluemix UI
2. Create a simple action accepting parameters (and expecting a parameter named message)
3. Expose the action via API GW (define a GET operation)
4. Try to he action via its route appending `?message=xyz`

## Provide the expected results and outputs:

Would expect a more precise error message indicating that the error is caused due to the fact that a default parameter called `message` already exists which cannot be overwritten by default.

## Provide the actual results and outputs:

```
“error”: “Request defines parameters that are not allowed (e.g., reserved properties).“,
  “code”: 736796
```

## Additional information you deem important:

Either change behavior or improve error message.

**Comment by rabbah** [comment] 2017-11-25 02:56
closing as duplicate of https://github.com/apache/incubator-openwhisk/issues/2163.

**Closed by rabbah** 2017-11-25 02:56 UTC
