### ISSUE TITLE
Scala compilaiton failure when using Java11 JDK

### ISSUE THREAD

**Issue by rahulqelfo** [apache/incubator-openwhisk#4181] opened 2018-12-16 14:19 UTC
All the tests are failing:

System:
Docker Version :18.06.1-ce
OS:Ubuntu 18.10

```
rahullfo@rahullfo-HP-Notebook:~/IdeaProjects/incubator-openwhisk$ ./gradlew tests:test
Starting a Gradle Daemon, 3 stopped Daemons could not be reused, use --status for details

> Task :core:invoker:compileScala
Pruning sources from previous analysis, due to incompatible CompileSetup.
/home/rahullfo/IdeaProjects/incubator-openwhisk/core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/docker/DockerClient.scala:164: value toSeq is not a member of java.util.stream.Stream[String]
    runCmd(cmd, config.timeouts.ps).map(_.lines.toSeq.map(ContainerId.apply))
                                                ^
/home/rahullfo/IdeaProjects/incubator-openwhisk/core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/docker/DockerClient.scala:164: missing argument list for method apply in object ContainerId
Unapplied methods are only converted to functions when a function type is expected.
You can make this conversion explicit by writing `apply _` or `apply(_)` instead of `apply`.
    runCmd(cmd, config.timeouts.ps).map(_.lines.toSeq.map(ContainerId.apply))
                                                                      ^
two errors found

> Task :core:invoker:compileScala FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':core:invoker:compileScala'.
> Compilation failed

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 54s
7 actionable tasks: 1 executed, 6 up-to-date
```
Any hint /tip

**Comment by rahulqelfo** [comment] 2018-12-16 20:40
Yup I am on master:
```
rahullfo@rahullfo-HP-Notebook:~/IdeaProjects/incubator-openwhisk$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```
Steps to Repro:
1) 

1. Clone https://github.com/apache/incubator-openwhisk-devtools.git
2. Navigate to incubator-openwhisk-devtools/docker-compose  and run 

make quick-start

This spins up the OW components
3. Clone https://github.com/apache/incubator-openwhisk.git
4. Now try running any of the tests mentioned in here -->https://github.com/apache/incubator-openwhisk/tree/master/tests

**Comment by rabbah** [comment] 2018-12-16 20:50
Ah - thanks for the extra details. I suspect that doesn't build all of openwhisk but will try again with these instructions to investigate.

@ddragosd might know faster.

**Comment by dgrove-oss** [comment] 2018-12-16 22:35
I've seen this Scala compilation error when the host JDK was Java10 (or Java11) instead of Java8.

There's something different about the map APIs in latest Java that imports into Scala slightly differently.

**Comment by csantanapr** [comment] 2018-12-17 02:02
Leave it open it would be good to find out how to make it work on java 11

**Comment by chetanmeh** [comment] 2019-01-15 06:35
Created #4217 to track work required to support JDK 11

**Comment by rabbah** [comment] 2019-02-06 23:52
closing as duplicate of #4217.

**Closed by rabbah** 2019-02-06 23:52 UTC

**Comment by williamgreenly** [comment] 2019-05-16 10:28
We're experiencing the same issue trying to install on Java12 JDK
