### ISSUE TITLE
wsk CLI is failing to create triggers with feed param

### ISSUE THREAD

**Issue by eweiter** [apache/incubator-openwhisk#2250] opened 2017-05-16 21:48 UTC
I have downloaded the latest CLI which has the following version and targeting Stage1
 "whisk API host		openwhisk.stage1.ng.bluemix.net
whisk API version	v1
whisk namespace		_
whisk CLI version	2017-05-12T06:48:31+00:00
whisk API build		2017-05-15T14:55:58Z
whisk API build number	whisk-build-4479"

I tried the following commands that I got from the documentation that is on the Bluemix documentation site: https://console.ng.bluemix.net/docs/openwhisk/openwhisk_github.html#openwhisk_catalog_github

I run the following two commands:
`wsk package bind /whisk.system/github myGit \
 --param username myGitUser \
 --param repository myGitRepo \
 --param accessToken aaaaa1111a1a1a1a1a111111aaaaaa1111aa1a1a`
then
`wsk trigger create myGitTrigger --feed myGit/webhook --param events push`

What I get back seems to be the CLI trying to invoke a trigger
```
erics-mbp:~/Dev/whisk/ui/Bluemix-Whisk-UI$ wsk trigger create myGitTrigger --feed myGit/webhook --param events push
ok: invoked /_/myGit/webhook with id bab26139bb324b33824975f6620bce49
{
    "activationId": "bab26139bb324b33824975f6620bce49",
    "annotations": [
        {
            "key": "limits",
            "value": {
                "logs": 10,
                "memory": 256,
                "timeout": 60000
            }
        },
        {
            "key": "path",
            "value": "whisk.system/github/webhook"
        }
    ],
    "duration": 10698,
    "end": 1494971164153,
    "logs": [],
    "name": "webhook",
    "namespace": "eweiter@us.ibm.com_dev2",
    "publish": false,
    "response": {
        "result": {
            "error": {
                "response": "{\"message\":\"Bad credentials\",\"documentation_url\":\"https://developer.github.com/v3\"}",
                "statusCode": 401
            }
        },
        "status": "application error",
        "success": false
    },
    "start": 1494971153455,
    "subject": "eweiter@us.ibm.com",
    "version": "0.0.145"
}
ok: invoked /_/myGit/webhook with id 8987040e6b044199bf2c4b848229576a
{
    "activationId": "8987040e6b044199bf2c4b848229576a",
    "annotations": [
        {
            "key": "limits",
            "value": {
                "logs": 10,
                "memory": 256,
                "timeout": 60000
            }
        },
        {
            "key": "path",
            "value": "whisk.system/github/webhook"
        }
    ],
    "duration": 10171,
    "end": 1494971174882,
    "logs": [],
    "name": "webhook",
    "namespace": "eweiter@us.ibm.com_dev2",
    "publish": false,
    "response": {
        "result": {
            "error": "Found no existing webhooks for trigger URL https://6779d970-ab27-4756-984e-23b5f7f38c92:U5d2nRsi3x6SYsmGscF4KXIO1ZIDLgramRLLFLLKTqS0gZ8OpzVluHRkMTN5WsWF@openwhisk.ng.bluemix.net/api/v1/namespaces/_/triggers/myGitTrigger"
        },
        "status": "application error",
        "success": false
    },
    "start": 1494971164711,
    "subject": "eweiter@us.ibm.com",
    "version": "0.0.145"
}
ok: deleted trigger myGitTrigger
Run 'wsk --help' for usage.
```

**Comment by rabbah** [comment] 2017-05-16 21:53
closing as duplicate of #2249.

**Closed by rabbah** 2017-05-16 21:53 UTC

**Comment by eweiter** [comment] 2017-05-17 14:58
@rabbah 
So mine is different from the one you linked to in that in my issue my trigger is never created. 
You can see from the output that at the end of the `wsk trigger create ...` command it for some reason appears to already delete my trigger 
```ok: deleted trigger myGitTrigger
Run 'wsk --help' for usage.```

I confirm this by running `wsk trigger list` and noticing that my trigger does not show up in the list.

I don't have permission to reopen this, but if you think it is different enough to reopen then you can, or I can copy what I have here into the other issue.

**Comment by rabbah** [comment] 2017-05-17 15:26
Your trigger is not created because: "Bad credentials" is reported by github.

**Comment by eweiter** [comment] 2017-05-17 15:29
@rabbah I saw that, but I don't know why it is saying that, I loaded my credentials from github.  I can create a package with no problems, actions, triggers. 

Just when I try to create a trigger with a feed I'm getting this output with Bad Credentials and the behavior.

**Comment by rabbah** [comment] 2017-05-17 15:36
OK the CLI appears to be working as expected in this case: feed fails, trigger deleted. I would open/move this issue to the catalog to investigate if there's a bug in the github feed action.

**Comment by eweiter** [comment] 2017-05-17 15:48
@rabbah 
disregard, user error, :(
I wasn't supplying the correct github creds just like the error message told me.
