### ISSUE TITLE
Authentication issues when installing openwhisk

### ISSUE THREAD

**Issue by elenagarrido** [apache/incubator-openwhisk#3529] opened 2018-04-06 11:21 UTC
## Environment details:

* windows 7
* Vagrant 2.0.2 
* Virtual Box Version 5.2.8 r121009

## Steps to reproduce the issue:

1. Execute  incubator-openwhisk/tools/vagrant/hello   

## Actual results and outputs:

The final output line is the following

The SSH command responded with a non-zero exit status. Vagrant assumes that this means the command failed. The output for this command should be in the log above. Please read the output to determine what went wrong.

Bellow you will find some logs where ansible failed.

```
  default: fatal: [ansible]: FAILED! => {"changed": true, "cmd": "./installRouteMgmt.sh /home/vagrant/openwhisk/ansible/files/auth.whisk.system
 172.17.0.1 /whisk.system /home/vagrant/openwhisk/bin/wsk", "delta": "0:00:00.351026", "end": "2018-04-06 10:46:46.769055", "msg": "non-zero retu
rn code", "rc": 145, "start": "2018-04-06 10:46:46.418029", "stderr": "+ '[' 4 -eq 0 ']'\n+ AUTH=/home/vagrant/openwhisk/ansible/files/auth.whisk
.system\n+ APIHOST=172.17.0.1\n+ NAMESPACE=/whisk.system\n+ WSK_CLI=/home/vagrant/openwhisk/bin/wsk\n+ WHISKPROPS_FILE=/home/vagrant/openwhisk/wh
isk.properties\n+ '[' -z '' ']'\n++ fgrep apigw.auth.user= /home/vagrant/openwhisk/whisk.properties\n++ cut -d= -f2\n+ GW_USER=\n+ '[' -z '' ']'\
n++ fgrep apigw.auth.pwd= /home/vagrant/openwhisk/whisk.properties\n++ cut -d= -f2-\n+ GW_PWD=\n+ '[' -z '' ']'\n++ cut -d= -f2\n++ fgrep apigw.h
ost.v2= /home/vagrant/openwhisk/whisk.properties\n+ GW_HOST_V2=http://172.17.0.1:9000/v2\n+ '[' -f /home/vagrant/openwhisk/ansible/files/auth.whi
sk.system ']'\n++ cat /home/vagrant/openwhisk/ansible/files/auth.whisk.system\n+ AUTH=$'789c46b1-71f6-4ed5-8c54-816aa4f8c502:abczO3xZCLrMN6v2BKK1
dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGuMDGIwP\\r'\n+ export WSK_CONFIG_FILE=\n+ WSK_CONFIG_FILE=\n+ echo Installing apimgmt package\n+ /home/vagra
nt/openwhisk/bin/wsk -i --apihost 172.17.0.1 package update --auth $'789c46b1-71f6-4ed5-8c54-816aa4f8c502:abczO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12Cd
AsMgRU4VrNZ9lyGVCGuMDGIwP\\r' --shared no /whisk.system/apimgmt -a description 'This package manages the gateway API configuration.' -p gwUser ''
 -p gwPwd '' -p gwUrlV2 http://172.17.0.1:9000/v2\nerror: Package update failed: The supplied authentication is invalid (code 3)", "stderr_lines"
: ["+ '[' 4 -eq 0 ']'", "+ AUTH=/home/vagrant/openwhisk/ansible/files/auth.whisk.system", "+ APIHOST=172.17.0.1", "+ NAMESPACE=/whisk.system", "+
 WSK_CLI=/home/vagrant/openwhisk/bin/wsk", "+ WHISKPROPS_FILE=/home/vagrant/openwhisk/whisk.properties", "+ '[' -z '' ']'", "++ fgrep apigw.auth.
user= /home/vagrant/openwhisk/whisk.properties", "++ cut -d= -f2", "+ GW_USER=", "+ '[' -z '' ']'", "++ fgrep apigw.auth.pwd= /home/vagrant/openw
hisk/whisk.properties", "++ cut -d= -f2-", "+ GW_PWD=", "+ '[' -z '' ']'", "++ cut -d= -f2", "++ fgrep apigw.host.v2= /home/vagrant/openwhisk/whi
sk.properties", "+ GW_HOST_V2=http://172.17.0.1:9000/v2", "+ '[' -f /home/vagrant/openwhisk/ansible/files/auth.whisk.system ']'", "++ cat /home/v
agrant/openwhisk/ansible/files/auth.whisk.system", "+ AUTH=$'789c46b1-71f6-4ed5-8c54-816aa4f8c502:abczO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4V
rNZ9lyGVCGuMDGIwP\\r'", "+ export WSK_CONFIG_FILE=", "+ WSK_CONFIG_FILE=", "+ echo Installing apimgmt package", "+ /home/vagrant/openwhisk/bin/ws
k -i --apihost 172.17.0.1 package update --auth $'789c46b1-71f6-4ed5-8c54-816aa4f8c502:abczO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGu
MDGIwP\\r' --shared no /whisk.system/apimgmt -a description 'This package manages the gateway API configuration.' -p gwUser '' -p gwPwd '' -p gwU
rlV2 http://172.17.0.1:9000/v2", "error: Package update failed: The supplied authentication is invalid (code 3)"], "stdout": "Installing apimgmt
package", "stdout_lines": ["Installing apimgmt package"]}
    default:
    default: [FAILED]
    default: > ./installRouteMgmt.sh /home/vagrant/openwhisk/ansible/files/auth.whisk.system 172.17.0.1 /whisk.system /home/vagrant/openwhisk/bin
/wsk
    default: non-zero return code
    default: Installing apimgmt package
    default: + '[' 4 -eq 0 ']' + AUTH=/home/vagrant/openwhisk/ansible/files/auth.whisk.system
    default: + APIHOST=172.17.0.1 + NAMESPACE=/whisk.system +
    default: WSK_CLI=/home/vagrant/openwhisk/bin/wsk +
    default: WHISKPROPS_FILE=/home/vagrant/openwhisk/whisk.properties + '[' -z '' ']' ++
    default: fgrep apigw.auth.user= /home/vagrant/openwhisk/whisk.properties ++ cut -d= -f2 +
    default: GW_USER= + '[' -z '' ']' ++ fgrep apigw.auth.pwd=
    default: /home/vagrant/openwhisk/whisk.properties ++ cut -d= -f2- + GW_PWD= + '[' -z ''
    default: ']' ++ cut -d= -f2 ++ fgrep apigw.host.v2=
    default: /home/vagrant/openwhisk/whisk.properties + GW_HOST_V2=http://172.17.0.1:9000/v2
    default: + '[' -f /home/vagrant/openwhisk/ansible/files/auth.whisk.system ']' ++ cat
    default: /home/vagrant/openwhisk/ansible/files/auth.whisk.system + AUTH=$'789c46b1-71f6-4
    default: ed5-8c54-816aa4f8c502:abczO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGu
    default: MDGIwP\r' + export WSK_CONFIG_FILE= + WSK_CONFIG_FILE= + echo Installing apimgmt
    default: package + /home/vagrant/openwhisk/bin/wsk -i --apihost 172.17.0.1 package update
    default: --auth $'789c46b1-71f6-4ed5-8c54-816aa4f8c502:abczO3xZCLrMN6v2BKK1dXYFpXlPkccOFq
    default: m12CdAsMgRU4VrNZ9lyGVCGuMDGIwP\r' --shared no /whisk.system/apimgmt -a
    default: description 'This package manages the gateway API configuration.' -p gwUser ''
    default: -p gwPwd '' -p gwUrlV2 http://172.17.0.1:9000/v2 error: Package update failed:
    default: The supplied authentication is invalid (code 3)
    default:
```

**Comment by mdeuser** [comment] 2018-04-06 12:57
@elenagarrido - can you run the following in your vagrant vm and post the results here
```
export TESTAUTH=/home/vagrant/openwhisk/ansible/files/auth.whisk.system
cat $TESTAUTH
TESTAUTH=`cat $TESTAUTH`
echo $TESTAUTH
```
in the above log output, it seems the `TESTAUTH` might be something odd like $'789c46b1-71f6-4ed5-8c54-816aa4f8c502:abczO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGuMDGIwP\r'

to confirm, in this same vagrant vm, create this simple script.  `chmod +x` it and then run it and post the output
```
#!/bin/bash
set -x
export TESTAUTH=/home/vagrant/openwhisk/ansible/files/auth.whisk.system
cat $TESTAUTH
TESTAUTH=`cat $TESTAUTH`
echo $TESTAUTH
```

**Comment by elenagarrido** [comment] 2018-04-09 09:38
Hello

thanks for the help.
Bellow you will find an image with the output. I hope it helps.
![openwhisk](https://user-images.githubusercontent.com/7858233/38490766-4c28e770-3bea-11e8-9323-5e2476a4493d.PNG)

**Comment by mdeuser** [comment] 2018-04-09 11:54
@elenagarrido - one minor correction.  in the line
```
TESTAUTH=`cat $TESTAUTH`
```
the quotes are back-tick characters, not single quote characters.  would you please correct the script and retry.

**Comment by elenagarrido** [comment] 2018-04-09 12:25
I've done it, sorry for the inconvenience.
Bellow you have the output:
![openwhisk](https://user-images.githubusercontent.com/7858233/38497566-d66cadd8-3c01-11e8-83f8-55bff8a0405c.PNG)

**Comment by mdeuser** [comment] 2018-04-13 12:59
hmm... that is unexpected behavior.  what version of the bash shell are you running?  when i run the same
```
TESTAUTH=`cat $TESTAUTH`
```
command in ubuntu 14.04 (bash version 4.3.11(1))  and 16.04 (bash version 4.3.48(1)) bash terminals, the output is the expected file contents without the `$` or surrounding single quotes.

**Comment by neerajmangal** [comment] 2018-04-13 15:26
@elenagarrido This is because of carriage return "\r" in the auth file, this might have added while transferring files from windows to ubuntu in vagrant sync.
 
To workaround remove '\r' from the auth.whisk.system and auth.guest. Give it a try. 

```vagrant ssh
cd /home/vagrant/openwhisk/ansible/files
sed 's/\r//g' auth.guest
sed 's/\r//g' auth.whisk.system
```

**Comment by regmebaby** [comment] 2018-04-17 08:08
I had the same issue. It is about Git and the handling of line endings. Try this to clone the repo:

```
git clone --depth=1 https://github.com/apache/incubator-openwhisk.git openwhisk --config core.autocrlf=input
```

Problem is: Git may checkout the files with CRLF-Endings on Windows and the VM interprets that files as LF-Ended. So the additional CR in front of the LF is interpreted to be part of the auth token.
Windows-Files linked into and interpreted by the Linux-VM 😃 

Maybe this should be added to the Quick Start Guide.

**Comment by mdeuser** [comment] 2018-04-17 13:56
would an update to https://github.com/apache/incubator-openwhisk/blob/master/.gitattributes be the permanent fix?
```
ansible/files/auth.guest text eol=lf
ansible/files/auth.whisk.system text eol=lf
```

**Comment by elenagarrido** [comment] 2018-04-18 09:17
I've tried the option of

`git clone --depth=1 https://github.com/apache/incubator-openwhisk.git openwhisk --config core.autocrlf=input`

When executing again the whole vagrant creation process I've got a different error. I have a comment of no space left on device. 

`default: TASK [cli : Copy expanded archive to final configuration directory] ************
default: Wednesday 18 April 2018  09:02:34 +0000 (0:00:00.644)       0:10:39.690 *******
default: fatal: [172.17.0.1]: FAILED! => {"changed": true, "cmd": "cp -r /home/vagrant/.openwhisk/ansible/tmp/wskconf/nginx/cli_temp/OpenWhisk_CLI/* /home/vagrant/.openwhisk/ansible/tmp/wskconf/nginx/cli/go/download", "delta": "0:00:00.158229", "end": "2018-04-18 09:02:34.501319", "msg
": "non-zero return code", "rc": 1, "start": "2018-04-18 09:02:34.343090", "stderr": "cp: error writing '/home/vagrant/.openwhisk/ansible/tmp/wskconf/nginx/cli/go/download/linux/arm64/OpenWhisk_CLI-linux-arm64.tgz': No space left on device\ncp: cannot create directory '/home/vagrant/.openw
hisk/ansible/tmp/wskconf/nginx/cli/go/download/mac': No space left on device\ncp: cannot create directory '/home/vagrant/.openwhisk/ansible/tmp/wskconf/nginx/cli/go/download/windows': No space left on device", "stderr_lines": ["cp: error writing '/home/vagrant/.openwhisk/ansible/tmp/wskconf/nginx/cli/go/download/linux/arm64/OpenWhisk_CLI-linux-arm64.tgz': No space left on device", "cp: cannot create directory '/home/vagrant/.openwhisk/ansible/tmp/wskconf/nginx/cli/go/download/mac': No space left on device", "cp: cannot create directory '/home/vagrant/.openwhisk/ansible/tmp/wskconf/nginx/cli/go/download/windows': No space left on device"], "stdout": "", "stdout_lines": []}`


A colleague is using the commit version 21d37a1af329544e245d376ad613d1a603fc104c and it running perfectly. I've tested the same version and have no issue with it. For some reason something has been changed and make the latest version fail.

**Comment by csantanapr** [comment] 2018-04-19 16:16
This is fixed now
https://github.com/apache/incubator-openwhisk/pull/3546
https://github.com/apache/incubator-openwhisk/pull/3561

**Closed by csantanapr** 2018-04-19 16:16 UTC
