### ISSUE TITLE
Packages should also be able to contain Triggers

### ISSUE THREAD

**Issue by ScottChapman** [apache/incubator-openwhisk#3247] opened 2018-02-05 14:59 UTC
I'm sure that this has been discussed at great length, so I apologize for bringing it up as an issue.

But it just seems arbitrary to me that Triggers cannot be in packages. Actions and Feeds (which themselves fire Trigger events) can be in Packages as a way to keep related artifacts together. Having Triggers be in the default package means one needs to rely on naming conventions to avoid conflict and to provide clarity.

Is there a technical reason why Triggers do not participate in packages?

**Comment by rabbah** [comment] 2018-02-05 15:08
Duplicate of https://github.com/apache/incubator-openwhisk/issues/1825.

There are some nuances for allowing a trigger and rule in a package. A trigger is usually created with a feed. So would one create a trigger in a package with a feed attached, and then permit bindings of that package? Is a trigger final and hence binding parameters don't extend to an established feed? What if a package with a trigger is shared?

These reasons and some historical artifacts of my original implementation is mostly why we haven't added this support yet.

**Comment by rabbah** [comment] 2018-02-05 15:10
Going to close in favor of #1825.

**Closed by rabbah** 2018-02-05 15:10 UTC
