### ISSUE TITLE
./gradlew distDocker build failed with two errors

### ISSUE THREAD

**Issue by varsha33** [apache/incubator-openwhisk#2290] opened 2017-05-25 02:27 UTC
vagrant@vagrant-ubuntu-trusty-64:~/openwhisk$ ./gradlew distDocker:common:scala:distDocker
Thu May 25 02:24:08 UTC 2017: Executing 'docker build -t scala /home/vagrant/openwhisk/common/scala'
Sending build context to Docker daemon 557.1 kB
Sending build context to Docker daemon 1.114 MB
Sending build context to Docker daemon 1.671 MB
Sending build context to Docker daemon 2.228 MB
Sending build context to Docker daemon 2.785 MB
Sending build context to Docker daemon 3.342 MB
Sending build context to Docker daemon 3.899 MB
Sending build context to Docker daemon 4.456 MB
Sending build context to Docker daemon 5.014 MB
Sending build context to Docker daemon 5.571 MB
Sending build context to Docker daemon 6.128 MB
Sending build context to Docker daemon 6.685 MB
Sending build context to Docker daemon 7.242 MB
Sending build context to Docker daemon 7.799 MB
Sending build context to Docker daemon 8.356 MB
Sending build context to Docker daemon 8.913 MB
Sending build context to Docker daemon  9.47 MB
Sending build context to Docker daemon 10.03 MB
Sending build context to Docker daemon 10.58 MB
Sending build context to Docker daemon 11.14 MB
Sending build context to Docker daemon  11.7 MB
Sending build context to Docker daemon 12.26 MB
Sending build context to Docker daemon 12.81 MB
Sending build context to Docker daemon 13.37 MB
Sending build context to Docker daemon 13.67 MB

Step 1 : FROM buildpack-deps:trusty-curl
 ---> b9a2d67cb24f
Step 2 : ENV DEBIAN_FRONTEND noninteractive
 ---> Using cache
 ---> d9d1543c038c
Step 3 : RUN locale-gen en_US.UTF-8
 ---> Using cache
 ---> f9a2c79681a3
Step 4 : ENV LANG en_US.UTF-8
 ---> Using cache
 ---> a025323b3ecf
Step 5 : ENV LANGUAGE en_US:en
 ---> Using cache
 ---> f7f24fe5dc46
Step 6 : ENV LC_ALL en_US.UTF-8
 ---> Using cache
 ---> 06ca4fdfdd85
Step 7 : ENV VERSION 8
 ---> Using cache
 ---> a7ddc0815db0
Step 8 : ENV UPDATE 121
 ---> Using cache
 ---> 195b0ed27c6e
Step 9 : ENV BUILD 13
 ---> Using cache
 ---> 7a8a3016c309
Step 10 : ENV JAVA_HOME /usr/lib/jvm/java-${VERSION}-oracle
 ---> Using cache
 ---> d81548806f0d
Step 11 : ENV JRE_HOME ${JAVA_HOME}/jre
 ---> Using cache
 ---> eb88c6dc380b
Step 12 : RUN curl --silent --location --retry 3 --cacert /etc/ssl/certs/GeoTrust_Global_CA.pem   --header "Cookie: oraclelicense=accept-securebackup-cookie;"   http://download.oracle.com/otn-pub/java/jdk/"${VERSION}"u"${UPDATE}"-b"${BUILD}"/e9e7ea248e2c4826b92b3f075a80e441/server-jre-"${VERSION}"u"${UPDATE}"-linux-x64.tar.gz   | tar xz -C /tmp &&   mkdir -p /usr/lib/jvm && mv /tmp/jdk1.${VERSION}.0_${UPDATE} "${JAVA_HOME}" &&   apt-get autoclean && apt-get --purge -y autoremove &&   rm -rf /tmp/* /var/tmp/*
 ---> Running in 9f28071de7e8

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
The command '/bin/sh -c curl --silent --location --retry 3 --cacert /etc/ssl/certs/GeoTrust_Global_CA.pem   --header "Cookie: oraclelicense=accept-securebackup-cookie;"   http://download.oracle.com/otn-pub/java/jdk/"${VERSION}"u"${UPDATE}"-b"${BUILD}"/e9e7ea248e2c4826b92b3f075a80e441/server-jre-"${VERSION}"u"${UPDATE}"-linux-x64.tar.gz   | tar xz -C /tmp &&   mkdir -p /usr/lib/jvm && mv /tmp/jdk1.${VERSION}.0_${UPDATE} "${JAVA_HOME}" &&   apt-get autoclean && apt-get --purge -y autoremove &&   rm -rf /tmp/* /var/tmp/*' returned a non-zero code: 2

Thu May 25 02:24:18 UTC 2017: Command 'docker build -t scala /home/vagrant/openwhisk/common/scala' failed with exitCode 2, 2 retries left, retrying...
Thu May 25 02:24:18 UTC 2017: Executing 'docker build -t scala /home/vagrant/openwhisk/common/scala'
Sending build context to Docker daemon 557.1 kB
Sending build context to Docker daemon 1.114 MB
Sending build context to Docker daemon 1.671 MB
Sending build context to Docker daemon 2.228 MB
Sending build context to Docker daemon 2.785 MB
Sending build context to Docker daemon 3.342 MB
Sending build context to Docker daemon 3.899 MB
Sending build context to Docker daemon 4.456 MB
Sending build context to Docker daemon 5.014 MB
Sending build context to Docker daemon 5.571 MB
Sending build context to Docker daemon 6.128 MB
Sending build context to Docker daemon 6.685 MB
Sending build context to Docker daemon 7.242 MB
Sending build context to Docker daemon 7.799 MB
Sending build context to Docker daemon 8.356 MB
Sending build context to Docker daemon 8.913 MB
Sending build context to Docker daemon  9.47 MB
Sending build context to Docker daemon 10.03 MB
Sending build context to Docker daemon 10.58 MB
Sending build context to Docker daemon 11.14 MB
Sending build context to Docker daemon  11.7 MB
Sending build context to Docker daemon 12.26 MB
Sending build context to Docker daemon 12.81 MB
Sending build context to Docker daemon 13.37 MB
Sending build context to Docker daemon 13.67 MB

Step 1 : FROM buildpack-deps:trusty-curl
 ---> b9a2d67cb24f
Step 2 : ENV DEBIAN_FRONTEND noninteractive
 ---> Using cache
 ---> d9d1543c038c
Step 3 : RUN locale-gen en_US.UTF-8
 ---> Using cache
 ---> f9a2c79681a3
Step 4 : ENV LANG en_US.UTF-8
 ---> Using cache
 ---> a025323b3ecf
Step 5 : ENV LANGUAGE en_US:en
 ---> Using cache
 ---> f7f24fe5dc46
Step 6 : ENV LC_ALL en_US.UTF-8
 ---> Using cache
 ---> 06ca4fdfdd85
Step 7 : ENV VERSION 8
 ---> Using cache
 ---> a7ddc0815db0
Step 8 : ENV UPDATE 121
 ---> Using cache
 ---> 195b0ed27c6e
Step 9 : ENV BUILD 13
 ---> Using cache
 ---> 7a8a3016c309
Step 10 : ENV JAVA_HOME /usr/lib/jvm/java-${VERSION}-oracle
 ---> Using cache
 ---> d81548806f0d
Step 11 : ENV JRE_HOME ${JAVA_HOME}/jre
 ---> Using cache
 ---> eb88c6dc380b
Step 12 : RUN curl --silent --location --retry 3 --cacert /etc/ssl/certs/GeoTrust_Global_CA.pem   --header "Cookie: oraclelicense=accept-securebackup-cookie;"   http://download.oracle.com/otn-pub/java/jdk/"${VERSION}"u"${UPDATE}"-b"${BUILD}"/e9e7ea248e2c4826b92b3f075a80e441/server-jre-"${VERSION}"u"${UPDATE}"-linux-x64.tar.gz   | tar xz -C /tmp &&   mkdir -p /usr/lib/jvm && mv /tmp/jdk1.${VERSION}.0_${UPDATE} "${JAVA_HOME}" &&   apt-get autoclean && apt-get --purge -y autoremove &&   rm -rf /tmp/* /var/tmp/*
 ---> Running in 578d6946c36e

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
The command '/bin/sh -c curl --silent --location --retry 3 --cacert /etc/ssl/certs/GeoTrust_Global_CA.pem   --header "Cookie: oraclelicense=accept-securebackup-cookie;"   http://download.oracle.com/otn-pub/java/jdk/"${VERSION}"u"${UPDATE}"-b"${BUILD}"/e9e7ea248e2c4826b92b3f075a80e441/server-jre-"${VERSION}"u"${UPDATE}"-linux-x64.tar.gz   | tar xz -C /tmp &&   mkdir -p /usr/lib/jvm && mv /tmp/jdk1.${VERSION}.0_${UPDATE} "${JAVA_HOME}" &&   apt-get autoclean && apt-get --purge -y autoremove &&   rm -rf /tmp/* /var/tmp/*' returned a non-zero code: 2

Thu May 25 02:24:27 UTC 2017: Command 'docker build -t scala /home/vagrant/openwhisk/common/scala' failed with exitCode 2, 1 retries left, retrying...
Thu May 25 02:24:27 UTC 2017: Executing 'docker build -t scala /home/vagrant/openwhisk/common/scala'
Sending build context to Docker daemon 557.1 kB
Sending build context to Docker daemon 1.114 MB
Sending build context to Docker daemon 1.671 MB
Sending build context to Docker daemon 2.228 MB
Sending build context to Docker daemon 2.785 MB
Sending build context to Docker daemon 3.342 MB
Sending build context to Docker daemon 3.899 MB
Sending build context to Docker daemon 4.456 MB
Sending build context to Docker daemon 5.014 MB
Sending build context to Docker daemon 5.571 MB
Sending build context to Docker daemon 6.128 MB
Sending build context to Docker daemon 6.685 MB
Sending build context to Docker daemon 7.242 MB
Sending build context to Docker daemon 7.799 MB
Sending build context to Docker daemon 8.356 MB
Sending build context to Docker daemon 8.913 MB
Sending build context to Docker daemon  9.47 MB
Sending build context to Docker daemon 10.03 MB
Sending build context to Docker daemon 10.58 MB
Sending build context to Docker daemon 11.14 MB
Sending build context to Docker daemon  11.7 MB
Sending build context to Docker daemon 12.26 MB
Sending build context to Docker daemon 12.81 MB
Sending build context to Docker daemon 13.37 MB
Sending build context to Docker daemon 13.67 MB

Step 1 : FROM buildpack-deps:trusty-curl
 ---> b9a2d67cb24f
Step 2 : ENV DEBIAN_FRONTEND noninteractive
 ---> Using cache
 ---> d9d1543c038c
Step 3 : RUN locale-gen en_US.UTF-8
 ---> Using cache
 ---> f9a2c79681a3
Step 4 : ENV LANG en_US.UTF-8
 ---> Using cache
 ---> a025323b3ecf
Step 5 : ENV LANGUAGE en_US:en
 ---> Using cache
 ---> f7f24fe5dc46
Step 6 : ENV LC_ALL en_US.UTF-8
 ---> Using cache
 ---> 06ca4fdfdd85
Step 7 : ENV VERSION 8
 ---> Using cache
 ---> a7ddc0815db0
Step 8 : ENV UPDATE 121
 ---> Using cache
 ---> 195b0ed27c6e
Step 9 : ENV BUILD 13
 ---> Using cache
 ---> 7a8a3016c309
Step 10 : ENV JAVA_HOME /usr/lib/jvm/java-${VERSION}-oracle
 ---> Using cache
 ---> d81548806f0d
Step 11 : ENV JRE_HOME ${JAVA_HOME}/jre
 ---> Using cache
 ---> eb88c6dc380b
Step 12 : RUN curl --silent --location --retry 3 --cacert /etc/ssl/certs/GeoTrust_Global_CA.pem   --header "Cookie: oraclelicense=accept-securebackup-cookie;"   http://download.oracle.com/otn-pub/java/jdk/"${VERSION}"u"${UPDATE}"-b"${BUILD}"/e9e7ea248e2c4826b92b3f075a80e441/server-jre-"${VERSION}"u"${UPDATE}"-linux-x64.tar.gz   | tar xz -C /tmp &&   mkdir -p /usr/lib/jvm && mv /tmp/jdk1.${VERSION}.0_${UPDATE} "${JAVA_HOME}" &&   apt-get autoclean && apt-get --purge -y autoremove &&   rm -rf /tmp/* /var/tmp/*
 ---> Running in 1d1a72b170a2

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
The command '/bin/sh -c curl --silent --location --retry 3 --cacert /etc/ssl/certs/GeoTrust_Global_CA.pem   --header "Cookie: oraclelicense=accept-securebackup-cookie;"   http://download.oracle.com/otn-pub/java/jdk/"${VERSION}"u"${UPDATE}"-b"${BUILD}"/e9e7ea248e2c4826b92b3f075a80e441/server-jre-"${VERSION}"u"${UPDATE}"-linux-x64.tar.gz   | tar xz -C /tmp &&   mkdir -p /usr/lib/jvm && mv /tmp/jdk1.${VERSION}.0_${UPDATE} "${JAVA_HOME}" &&   apt-get autoclean && apt-get --purge -y autoremove &&   rm -rf /tmp/* /var/tmp/*' returned a non-zero code: 2

Thu May 25 02:24:38 UTC 2017: Command 'docker build -t scala /home/vagrant/openwhisk/common/scala' failed with exitCode 2, no more retries left, aborting...
:common:scala:distDocker FAILED
:common:scala:tagImage
Thu May 25 02:24:39 UTC 2017: Executing 'docker tag scala whisk/scala:latest'
Error response from daemon: no such id: scala
Thu May 25 02:24:39 UTC 2017: Command 'docker tag scala whisk/scala:latest' failed with exitCode 1, 2 retries left, retrying...
Thu May 25 02:24:39 UTC 2017: Executing 'docker tag scala whisk/scala:latest'
Error response from daemon: no such id: scala
Thu May 25 02:24:39 UTC 2017: Command 'docker tag scala whisk/scala:latest' failed with exitCode 1, 1 retries left, retrying...
Thu May 25 02:24:39 UTC 2017: Executing 'docker tag scala whisk/scala:latest'
Error response from daemon: no such id: scala
Thu May 25 02:24:39 UTC 2017: Command 'docker tag scala whisk/scala:latest' failed with exitCode 1, no more retries left, aborting...
:common:scala:tagImage FAILED

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Script '/home/vagrant/openwhisk/gradle/docker.gradle' line: 96

* What went wrong:
Execution failed for task ':common:scala:distDocker'.
> Thu May 25 02:24:38 UTC 2017: Command 'docker build -t scala /home/vagrant/openwhisk/common/scala' failed with exitCode 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
==============================================================================

2: Task failed with an exception.
-----------
* Where:
Script '/home/vagrant/openwhisk/gradle/docker.gradle' line: 96

* What went wrong:
Execution failed for task ':common:scala:tagImage'.
> Thu May 25 02:24:39 UTC 2017: Command 'docker tag scala whisk/scala:latest' failed with exitCode 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
==============================================================================

BUILD FAILED

Total time: 32.929 secs

**Comment by Little-gg** [comment] 2017-05-26 13:12
I have met the same issue, this may be curl header is not working while downloading oracle jre from oracle website.  You may try my patch which works for me:
`diff --git a/common/scala/Dockerfile b/common/scala/Dockerfile
index 78ff867..d5fe34b 100644
--- a/common/scala/Dockerfile
+++ b/common/scala/Dockerfile
@@ -15,7 +15,7 @@ ENV JAVA_HOME /usr/lib/jvm/java-${VERSION}-oracle
 ENV JRE_HOME ${JAVA_HOME}/jre

 RUN curl --silent --location --retry 3 --cacert /etc/ssl/certs/GeoTrust_Global_CA.pem \
-  --header "Cookie: oraclelicense=accept-securebackup-cookie;" \
+  -b "oraclelicense=a" \
   http://download.oracle.com/otn-pub/java/jdk/"${VERSION}"u"${UPDATE}"-b"${BUILD}"/d54c1d3a095b4ff2b6607d096fa80163/server-jre-"${VERSION}"u"${UPDATE}"-linux-x64.tar.gz \
   | tar xz -C /tmp && \
   mkdir -p /usr/lib/jvm && mv /tmp/jdk1.${VERSION}.0_${UPDATE} "${JAVA_HOME}" && \`

**Comment by Joranson** [comment] 2017-05-27 00:59
same issue here. @Little-gg I manually made the changes you post, but it still doesn't work. Any suggestions would be much appreciated!

**Comment by Little-gg** [comment] 2017-05-27 02:19
@Joranson try the following codes to check whether you can download java outside your container:
```
VERSION=8
UPDATE=131
BUILD=11
curl -L -b "oraclelicense=a" http://download.oracle.com/otn-pub/java/jdk/"${VERSION}"u"${UPDATE}"-b"${BUILD}"/d54c1d3a095b4ff2b6607d096fa80163/server-jre-"${VERSION}"u"${UPDATE}"-linux-x64.tar.gz -O
```
Check your curl output, and you may see the progress. If java is in downloading progress, that means that is the docker issue, not the curl issue.

**Comment by varsha33** [comment] 2017-05-27 03:50
Thank you for your reply @Little-gg

**Comment by Joranson** [comment] 2017-05-29 22:02
@Little-gg Thanks! I believe it's a docker issue.

**Comment by rabbah** [comment] 2017-05-30 15:47
A few days ago our CI was also affected - we bumped the JDK version - is this still an issue if you're on master?

**Comment by Little-gg** [comment] 2017-05-31 04:57
@rabbah I tried the latest version with commit #e6942ec and it is still an issue for me.
 I recommend to use http header '-b "oraclelicense=a"' instead of '--header "Cookie: oraclelicense=accept-securebackup-cookie;"' which may be a better choice.

**Comment by Joranson** [comment] 2017-05-31 22:18
@Little-gg @rabbah I actually fixed it by pulling the **latest commit** from master branch. Hope this helps!

**Comment by bhkim1020** [comment] 2017-06-01 02:33
@Little-gg I also have a same problem.
I tried to modify Dockerfile following.
RUN curl -v --silent --location --retry 3 --cacert /etc/ssl/certs/GeoTrust_Global_CA.pem \
  -b "oraclelicense=a" \
~~~~~(the same code as commited)

However, I confirmed the following message and it was not executed ./distDocker
Is there anyone like me?

Step 12/13 : RUN curl -v --silent --location --retry 3 --cacert /etc/ssl/certs/GeoTrust_Global_CA.pem   -b "oraclelicense=a"   http://download.oracle.com/otn-pub/java/jdk/"${VERSION}"u"${UPDATE}"-b"${BUILD}"/d54c1d3a095b4ff2b6607d096fa80163/server-jre-"${VERSION}"u"${UPDATE}"-linux-x64.tar.gz   | tar xz -C /tmp &&   mkdir -p /usr/lib/jvm && mv /tmp/jdk1.${VERSION}.0_${UPDATE} "${JAVA_HOME}" &&   apt-get autoclean && apt-get --purge -y autoremove &&   rm -rf /tmp/* /var/tmp/*
 ---> Running in bc414b41f07f
* Hostname was NOT found in DNS cache
* Could not resolve host: download.oracle.com
* Closing connection 0

**Comment by csantanapr** [comment] 2017-06-08 13:52
This is fix now with https://github.com/apache/incubator-openwhisk/commit/c036e0d1ee0be312dc5cc43cb2263ab3f0073b87

**Closed by csantanapr** 2017-06-08 13:52 UTC
